FROM nvcr.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
      ca-certificates \
      python3 \
      python3-pip \
      python3-venv \
      git \
      build-essential \
      cmake \
      libopencv-dev \
      libtclap-dev \
      libmagic-dev \
      libprotobuf-dev \
      libprotoc-dev \
      protobuf-compiler \
      file \
      wget && \
    update-ca-certificates && \
    pip3 install --no-cache-dir --break-system-packages \
      jupyterlab \
      notebook && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

RUN git clone https://codeberg.org/CCodeRun/darknet.git darknet-build && \
    cd darknet-build && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CUDA_FLAGS="--generate-code=arch=compute_75,code=sm_75 \
                              --generate-code=arch=compute_80,code=sm_80 \
                              --generate-code=arch=compute_86,code=sm_86 \
                              --generate-code=arch=compute_89,code=sm_89 \
                              --generate-code=arch=compute_90,code=sm_90 \
                              --generate-code=arch=compute_120,code=sm_120" .. && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    rm -rf /usr/src/darknet-build

WORKDIR /usr/src

RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/lib/libcuda.so.1 && \
    git clone https://codeberg.org/CCodeRun/DarkHelp.git darkhelp-build && \
    cd darkhelp-build && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make -j$(nproc) && \
    make install && \
    rm -f /usr/lib/libcuda.so.1 && \
    ldconfig && \
    rm -rf /usr/src/darkhelp-build

WORKDIR /workspace

CMD ["jupyter", "lab", \
     "--ip=0.0.0.0", \
     "--port=8888", \
     "--no-browser", \
     "--allow-root", \
     "--NotebookApp.token=''"]